version: '3'
services:
  registry-ui:
    image: konradkleine/docker-registry-frontend:v2
    container_name: registry_ui
    restart: always
    privileged: true
    environment:
      - ENV_DOCKER_REGISTRY_HOST=192.168.80.20
      - ENV_DOCKER_REGISTRY_PORT=5000
    ports:
      - "5001:80"